# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
# .circleci/config.yml
version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.0
  gcp-gke: circleci/gcp-gke@0.1.0
  featurepeek: featurepeek/ping@0.0.2

executors:
  default:
    machine: true

jobs:
  build_and_push_image:
    executor: default
    steps:
      - checkout
      - run: env > .env.production
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: ${CIRCLE_PROJECT_REPONAME}
          tag: ${CIRCLE_BRANCH}
      - gcp-gcr/push-image:
          image: ${CIRCLE_PROJECT_REPONAME}
          tag: ${CIRCLE_BRANCH} 
  deploy_dev:
    executor: default 
    steps:
      - gcp-gcr/gcr-auth
      - gcp-gke/rollout-image:
          deployment: ${DEV_CLUSTER_NAME}
          container: ${CIRCLE_PROJECT_REPONAME}
          image: gcr.io/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}-${CIRCLE_SHA1}

workflows:
  build_and_push_image:
    jobs:
      - build_and_push_image
      - gcp-gcr/add-image-tag:
          requires:
            - build_and_push_image
          # filters:
          #   branches:
          #     only: [master, dev]
          image: ${CIRCLE_PROJECT_REPONAME}
          registry-url: gcr.io
          source-tag: ${CIRCLE_BRANCH}
          target-tag: ${CIRCLE_BRANCH}-${CIRCLE_SHA1}
      - deploy_dev:
          requires:
            - build_and_push_image
            - gcp-gcr/add-image-tag
          # filters:
          #   branches:
          #     only: [dev]
      - featurepeek/ping_featurepeek:
          requires:
            - build_and_push_image
          image: ${CIRCLE_PROJECT_REPONAME}
          tag: ${CIRCLE_BRANCH}
          env: dev
          filters:
            branches:
              ignore: [master, dev]

