# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
# .circleci/config.yml
version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.3.0
  featurepeek: featurepeek/ping@0.0.2

executors:
  default:
    description: A debian-based machine executor
    machine: true

jobs:
  build-image:
    executor: default
    steps:
      - checkout
      - run: env > .env.production
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: marketing-website
          tag: latest

  # build-image: 
  #   executor: default
  #   steps:
  #     - gcp-gcr/gcr-auth
  #     - gcp-gcr/build-image:
  #         image: marketing-website
  #         tag: latest
      

workflows:
  build_and_push_image:
    jobs:
      # - setup-checkout
      - build-image: 
          # requires: 
          #   - setup-checkout

           
      # - featurepeek/ping_featurepeek:
      #     requires:
      #       - gcp-gcr/build-and-push-image
      #     image: marketing-website
      #     tag: latest
      #     env: dev
