# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
# .circleci/config.yml
version: 2.1

executors:
  my-executor: shell

jobs:
  setup_env:
    executor: my-executor
    steps:
      - run: 'env > .env.production'


orbs:
  gcp-gcr: circleci/gcp-gcr@0.3.0
  featurepeek: featurepeek/ping@0.0.2
  workflows:
    build_and_push_image:
      jobs:
        - gcp-gcr/build-and-push-image:
            image: marketing-website
            tag: latest
            requires:
              - setup_env
        - featurepeek/ping_featurepeek:
            requires:
              - gcp-gcr/build-and-push-image
            image: marketing-website
            tag: latest
            env: dev
